version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  db:
    image: sqlite:latest
    volumes:
      - grade-tracker/grades.db:/grades.db
